apiVersion: v1
kind: Service
metadata:
  name: {{ include "codesys-control-sl.fullname" . }}
  labels:
    {{- include "codesys-control-sl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
      protocol: TCP
      name: gateway
    - port: {{ .Values.service.webVisuPort }}
      targetPort: webvisu
      protocol: TCP
      name: webvisu
    - port: {{ .Values.service.opcuaPort }}
      targetPort: opcua
      protocol: TCP
      name: opcua
  selector:
    {{- include "codesys-control-sl.selectorLabels" . | nindent 4 }}
