apiVersion: v2
name: codesys-app
description: CODESYS Control SL Runtime for Linux x86/AMD64 — IEC 61131-3 PLC (prebuilt image)
type: application
version: 1.4.1
appVersion: "4.20.0.0"
keywords:
  - codesys
  - plc
  - industrial
  - amd64
  - x86
  - iiot
  - iec-61131
  - opc-ua
  - webvisu
home: https://github.com/Embernet-ai/Codesys-AMD-64-x86
icon: https://avatars.githubusercontent.com/u/88027827?v=4
maintainers:
  - name: Embernet-ai
    email: support@embernet.ai
annotations:
  catalog.cattle.io/display-name: "CODESYS Control SL (AMD64)"
  catalog.cattle.io/os: linux
  catalog.cattle.io/arch: amd64
  catalog.cattle.io/certified: partner
  catalog.cattle.io/release-name: codesys-app
  catalog.cattle.io/namespace: industrial
  catalog.cattle.io/kube-version: ">=1.19.0-0"
  catalog.cattle.io/rancher-version: ">=2.5.0-0"
  catalog.cattle.io/upstream-version: "4.20.0.0"
